---
swagger: "2.0"
info:
  title: dropoff_location
  version: 1.0.0
definitions:
  dropoff_location:
    title: Dropoff Location
    description: Rental car dropoff location and address information.
    required:
    - address
    type: object
    properties:
      location:
        $ref: '#/definitions/location'
        description: ""
      address:
        $ref: '#/definitions/address'
        description: ""
  location:
    $ref: apicurio:90#/definitions/location
  address:
    $ref: apicurio:91#/definitions/address
