---
swagger: "2.0"
info:
  title: taxes
  version: 1.0.0
paths:
  /v1: {}
definitions:
  taxes:
    title: Rental Taxes
    description: Taxes applied to the reservation in the localized currency.
    type: array
    items:
      properties:
        type:
          description: The type of taxation to be applied.
          enum:
          - Standard
          - GST
          type: string
          example: GST
        amount:
          description: The cost of taxes for the reservation.
          type: number
